NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: ""
MODEL:
  TYPE: "vit"
  LINEAR:
    MLP_SIZES: []
SOLVER:
  SCHEDULER: "cosine"
  LOSS: "softmax"
  OPTIMIZER: "sgd"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
DATA:
  NAME: ""
  NUMBER_CLASSES: -1
  ROOT: ""
  BATCH_SIZE: 64
