_BASE_: "../base-prompt.yaml"
NUM_GPUS: 4
DATA:
  NAME: "cifar10"
  ROOT: "/mnt/data/ztl/mycode/data"
  NUMBER_CLASSES: 10
  BATCH_SIZE: 64
  FEATURE: "sup_vitb16_imagenet21k"
MODEL:
  TRANSFER_TYPE: "prompt"
  TYPE: "vit"
  MODEL_ROOT: "./weights"
  MODEL_NAME: "imagenet21k_ViT-B_16.npz"
  PROMPT:
    DEEP: True
    DROPOUT: 0.1
    NUM_TOKENS: 10
SOLVER:
  BASE_LR: 0.05
  WEIGHT_DECAY: 0.01
OUTPUT_DIR: "./output"
