_BASE_: "../base-prompt.yaml"
NUM_GPUS: 2
DATA:
  NAME: "cifar100"
  ROOT: "/root/autodl-tmp/data"
  NUMBER_CLASSES: 100
  MULTILABEL: False
  BATCH_SIZE: 64
  FEATURE: "sup_vitb16_imagenet21k"
MODEL:
  TRANSFER_TYPE: "linear"
  TYPE: "vit"
  MODEL_ROOT: "./weights"
  MODEL_NAME: "imagenet21k_ViT-B_16.npz"
  PROMPT:
    DEEP: True
    DROPOUT: 0.1
    NUM_TOKENS: 10
SOLVER:
  BASE_LR: 0.05
  WEIGHT_DECAY: 0.01
OUTPUT_DIR: "./output"
