_BASE_: "../base-simple.yaml"
NUM_GPUS: 2
DATA:
  NAME: "cifar100-lt"
  ROOT: "/root/autodl-tmp/data"
  NUMBER_CLASSES: 100
  BATCH_SIZE: 64
MODEL:
  TRANSFER_TYPE: "linear"
  TYPE: "vit"
  MODEL_ROOT: "./weights"
  MODEL_NAME: "vit_base_patch16_224_augreg_in21k.pth"
SOLVER:
  BASE_LR: 0.05
  WEIGHT_DECAY: 0.01
OUTPUT_DIR: "./output"
